name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  test:
    name: Automatic Style Checker, Bug Finder, and Test Suite Runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify and Fail on Checkstyle Warnings
        run: mvn -B clean verify checkstyle:check -Dcheckstyle.failOnViolation=true
      - name: Run PMD Static Analysis
        run: |
          mvn pmd:pmd \
            -Dpmd.rulesets=category/java/bestpractices.xml,category/java/codestyle.xml,category/java/design.xml \
            -Dpmd.format=text \
            -Dpmd.analysisCache=true